In [1]:
import tensorflow as tf
import numpy as np

In [2]:
graph = tf.Graph()

In [3]:
with graph.as_default():
    with tf.variable_scope("theta", reuse=tf.AUTO_REUSE):
        theta = tf.get_variable("theta", shape=[1, 3], initializer=tf.ones_initializer())
        theta = theta.assign(np.array([[1, 2, 3]]))
    x = tf.placeholder(name="x", shape=[1, 3], dtype=tf.float32)
    y = tf.matmul(x, tf.transpose(theta))
    with tf.Session() as sess:
        sess.run(tf.global_variables_initializer())
        res = sess.run(y, feed_dict={x: np.array([[1, 2, 3]])})
        print(res)

[[ 14.]]


In [4]:
sess = tf.InteractiveSession()

In [78]:
# compute euclid distance
X = tf.constant([[1., 1.], [2., 2.], [3., 3.]])
centroids = tf.constant([[1., 0.5], [2., 2.5]])
K = 2
def get_distance(X, vector):
    m, n = X.shape
    distance = tf.reshape(tf.sqrt(tf.reduce_sum(tf.square(X - vector), axis=1)), [m, 1])
    return distance

distances = []
for i in range(K):
    d = get_distance(X, centroids[i])
    distances.append(d)
# assign centers to each row    
distances = tf.concat(distances, axis=1) # concated by column, distances[:, 1] is the distance between X and center 1
idx = tf.argmin(distances, axis=1) # get the index of minumum distances for each sample
print(sess.run(distances))
print(sess.run(idx))

[[ 0.5         1.80277562]
 [ 1.80277562  0.5       ]
 [ 3.20156217  1.11803401]]
[0 1 1]


In [76]:
X = tf.constant([[1., 1.], [2., 2.], [3., 3.]])
b = tf.reduce_sum(X, keep_dims=False, axis=1)
b = tf.reshape(b, [3, 1])

[0, 1]

In [68]:
# random select centers
K = 2
X = tf.constant([[1., 0.], [0, 1], [2., 2.], [3., 3.]])
rand_centers = tf.random_shuffle(X)[:K,]
print(sess.run(rand_centers))

[[ 3.  3.]
 [ 2.  2.]]


In [89]:
# Compute centroids
X = tf.constant([[1., 0.], [0, 1], [2., 2.], [3., 3.]])
idx = tf.constant([0, 0, 1, 1])
K = 2
m, n = X.shape
with tf.variable_scope("centers", reuse=tf.AUTO_REUSE):
    centroids = tf.get_variable("centers", shape=[K, n], initializer=tf.ones_initializer())
    
def compute_centroid(X, idx, k):
    m, n = X.shape
    cluster_no = tf.ones(idx.shape, dtype=tf.int32) * k
    mask = tf.equal(idx, cluster_no)
    center_group = tf.boolean_mask(X, mask)
    center = tf.reshape(tf.reduce_mean(center_group, axis=0), [1, n])
    return center
sess.run(centroids.initializer)
centers = []
for i in range(K):
    center = compute_centroid(X, idx, i)
    centers.append(center)
centers = tf.concat(centers, axis=0)
op = centroids.assign(centers)
print sess.run(op)


[[ 0.5  0.5]
 [ 2.5  2.5]]


In [208]:
sess = tf.InteractiveSession()
with tf.variable_scope("v", reuse=tf.AUTO_REUSE):
    v = tf.get_variable("v", shape=[2, 2], initializer=tf.zeros_initializer())
sess.run(v.initializer)

<tf.Tensor 'strided_slice_102/_assign:0' shape=(2, 2) dtype=float32_ref>

In [223]:
v[1, :]

<tf.Tensor 'strided_slice_103:0' shape=(2,) dtype=float32>

In [83]:
X = tf.constant([[1., 0.], [0, 1], [2., 2.], [3., 3.]])
tf.boolean_mask(X, [False, True, True, False])

<tf.Tensor 'boolean_mask_38/Gather:0' shape=(?, 2) dtype=float32>

In [86]:
n = tf.constant([1, 1]).shape

In [90]:
sess.run(tf.reshape([1, 2], [1, 2]) * 2)

array([[2, 4]], dtype=int32)